### PR TITLE
Process entire stack subtree when syncing stack

### PR DESCRIPTION
**Pull request by oleg-codaio**
When running `av stack sync`, sync the entire "stack" (starting from root) instead of just the subtree from the current branch.

Updated test to document new behavior.

### CODE REVIEW

**Comment by draftcode** [comment]
Isn't this effectively behave same as always specifying `--all` as `av` doesn't support non-default (== branches other than refs/remotes/origin/HEAD) trunk branch?

**Comment by oleg-codaio** [comment]
It's different in my testing, since `av stack sync` will only sync the current stack from the root node - not from other root nodes going off the trunk branch.

Consider the following set up - I have two stacks I made off `main`:
- `main` -> `add-foo-txt-1` -> `add-bar-txt-1`
- `main` -> `add-foo-txt-2` -> `add-bar-txt-2`

Here's what `av stack tree` reports:

```
➜  test-stack git:(add-bar-txt-2) av stack tree
  * add-bar-txt-2 (HEAD)
  │ https://github.com/oleg-codaio/test-stack/pull/28
  │
  * add-foo-txt-2
  │ https://github.com/oleg-codaio/test-stack/pull/27
  │
  │ * add-bar-txt-1
  │ │ https://github.com/oleg-codaio/test-stack/pull/26
  │ │
  │ * add-foo-txt-1
  │ │ https://github.com/oleg-codaio/test-stack/pull/25
  ├─┘
  * main
```

If I ran `av st sync`:

```
➜  test-stack git:(add-bar-txt-2) av st sync                                            
Synchronizing branch add-foo-txt-2...
  - fetching latest pull request information for add-foo-txt-2
  - branch is a stack root, nothing to do (run av stack sync --trunk to sync against the latest commit in main)
  - not pushing branch add-foo-txt-2 (upstream is already up-to-date)


Synchronizing branch add-bar-txt-2...
  - fetching latest pull request information for add-bar-txt-2
  - already up-to-date with parent add-foo-txt-2
  - not pushing branch add-bar-txt-2 (upstream is already up-to-date)
```

it only syncs the current stack. On the other hand, if I run `av st sync --all`, it syncs all my stacks:

```
➜  test-stack git:(add-bar-txt-2) av st sync --all
Synchronizing branch add-foo-txt-1...
  - fetching latest pull request information for add-foo-txt-1
  - branch is a stack root, nothing to do (run av stack sync --trunk to sync against the latest commit in main)
  - not pushing branch add-foo-txt-1 (upstream is already up-to-date)


Synchronizing branch add-bar-txt-1...
  - fetching latest pull request information for add-bar-txt-1
  - already up-to-date with parent add-foo-txt-1
  - not pushing branch add-bar-txt-1 (upstream is already up-to-date)


Synchronizing branch add-foo-txt-2...
  - fetching latest pull request information for add-foo-txt-2
  - branch is a stack root, nothing to do (run av stack sync --trunk to sync against the latest commit in main)
  - not pushing branch add-foo-txt-2 (upstream is already up-to-date)


Synchronizing branch add-bar-txt-2...
  - fetching latest pull request information for add-bar-txt-2
  - already up-to-date with parent add-foo-txt-2
  - not pushing branch add-bar-txt-2 (upstream is already up-to-date)
```

**Comment by draftcode** [comment]
Oh. OK. I see. So, sync will target:

* Current behavior: branches between trunk and current branch + current branch + children
* `--all` behavior: all branches
* New behavior: children of the stack root (the branch right next to trunk)

**Review by draftcode — APPROVED** [review]

**Comment by oleg-codaio** [comment]
Yup, exactly. It will now include all the "cousins" of the current branch in its stack.

**Pull request merged**
